services:
  backend:
    build: socialmedia-webservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/demo
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=${H2_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - WEB_DRIVER_PATH=/usr/bin/chromedriver
    env_file:
      - secrets.env
    networks:
      - socialmedia-net

  frontend:
    build: socialmedia-fe
    ports:
      - "4201:80"
    networks:
      - socialmedia-net

networks:
  socialmedia-net:
